name: Generate Pac-Man Snake

on:
  schedule:
    - cron: "0 0 * * *" # Har din raat 12 baje chalega
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pac-Man SVG
        uses: Platane/snk@master
        with:
          github_user_name: shubham055555
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: "#FFFF00"  # Pac-Man yellow
          color_dots: "#000000,#333333,#666666,#999999,#CCCCCC"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
